IndividualTaskManagement/Controllers/GoalController.cs
using IndividualTaskManagement.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;


namespace IndividualTaskManagement.Controllers
{
    public class GoalController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Task

        [Authorize(Roles = "teacher")]
        public ActionResult Index()
        {
            
            string user = User.Identity.GetUserId();
            var goal = db.Goal.Include(l => l.Author).Where(l => l.Author.Id == user);                        
            return View(goal.ToList());
        }

        [Authorize(Roles = "teacher")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddGoalModel goalview)
        {
            if (ModelState.IsValid)
            {
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                var goal = new Goal() { Name = goalview.name, Subject = db.Subject.Find(goalview.subject_id)};
                goal.StartDate = DateTime.Now;
                goal.Author = userManager.FindById(User.Identity.GetUserId());
                goal.Completeness = 0;
                db.Goal.Add(goal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(goalview);
        }

        [Authorize(Roles = "teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goal goal = db.Goal.Find(id);            
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(new AddGoalModel(goal));
        }



        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AddGoalModel goalview)
        {
            if (ModelState.IsValid)
            {
                var goal = db.Goal.Find(goalview.id);
                goal.Name = goalview.name;                
                goal.Subject = db.Subject.Find(goalview.subject_id);
                db.Entry(goal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(goalview);
        }

        [Authorize(Roles = "teacher, admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goal goal = db.Goal.Find(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }



        [Authorize(Roles = "teacher, admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
          
            Goal goal = db.Goal.Find(id);
          
            db.Goal.Remove(goal);
            db.SaveChanges();
            if (User.IsInRole("admin"))
            {

                return RedirectToAction("List");
            }
            else
            {

                return RedirectToAction("Index");
            }
        }   

        [Authorize(Roles = "teacher")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goal goal = db.Goal.Find(id);           
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

    }
}

IndividualTaskManagement/Controllers/SubgoalController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using Microsoft.Owin.Security;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using IndividualTaskManagement.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;

namespace IndividualTaskManagement.Controllers
{
    public class SubgoalController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private ApplicationDbContext db = new ApplicationDbContext();
       
        // GET: Subgoal
        [Authorize(Roles = "student")]
        public ActionResult Index()
        {
            string user = User.Identity.GetUserId();
            var subgoal = db.Subgoal.Include(s => s.Student).Where(s => s.Student.Id == user);
            return View(subgoal.ToList());
        }  

        [Authorize(Roles = "student, teacher")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Subgoal subgoal = db.Subgoal.Find(id);
            if (subgoal.EndDate < DateTime.Now)
            {
                subgoal.Overdue = true;
            }
            var folder = Server.MapPath("/Files/" + id + "");
            try
            {
                ViewBag.CountFiles = new DirectoryInfo(folder).GetFiles().Length;
            }
            catch (DirectoryNotFoundException)
            {
                ViewBag.CountFiles = 0;
                //For successful entering to repository
            }           
            //ViewBag.Student = IsNeededStudent(subgoal.Student.Id);
            if (subgoal == null)
            {
                return HttpNotFound();
            }
            return View(subgoal);
        }


        [HttpPost]
        public ActionResult Details(int id)
        {
            Subgoal subgoal = db.Subgoal.Find(id);
            if (subgoal.EndDate < DateTime.Now)
            {
                subgoal.Overdue = true;
            }
       
            ViewBag.IsOverdue = subgoal.Overdue;
    
            if (HttpContext.Request.Files.AllKeys.Any())
            {
                for (int i = 0; i <= HttpContext.Request.Files.Count; i++)
                {
                    var file = HttpContext.Request.Files["files" + i];
                    if (file != null)
                    {
                        var folder = Server.MapPath("/Files/" + id + "");
                     
                        var fileSavePath = Path.Combine(folder, file.FileName);
                        if (!Directory.Exists(folder))
                        {
                            Directory.CreateDirectory(folder);
                        }
                        file.SaveAs(fileSavePath);

                    }
                }
            }
            return View(subgoal);
        }


        public ActionResult Download(int? subgoalId)
        {
            Subgoal subgoal = db.Subgoal.Find(subgoalId);

            try
            {
                string[] files = Directory.GetFiles(Server.MapPath("/Files/" + subgoalId + ""));
                string[] dates = new string[files.Count()];
                string[] length = new string[files.Count()];
                for (int i = 0; i < files.Length; i++)
                {
                    FileInfo oFileInfo = new FileInfo(files[i]);
                    dates[i] = oFileInfo.CreationTime.ToString();
                    if (oFileInfo.Length >= (1 << 20))
                    {
                        length[i] = string.Format("{0} megabytes", oFileInfo.Length >> 20);
                    }
                    else if (oFileInfo.Length >= (1 << 10))
                    {
                        length[i] = string.Format("{0} kilobytes", oFileInfo.Length >> 10);
                    }
                    else if (oFileInfo.Length < (1 << 10))
                    {
                        length[i] = string.Format("{0} bytes", oFileInfo.Length);
                    }
                                  
                    files[i] = Path.GetFileName(files[i]);
                }
                ViewBag.Files = files;
                ViewBag.Dates = dates;
                ViewBag.Length = length;
                ViewBag.id = subgoalId;
            }
            catch (DirectoryNotFoundException)
            {
                //For successful entering to repository
            }
            return View(subgoal);
        }


        public FileResult DownloadFile(string fileName, int subgoalId)
        {
            var filepath = Path.Combine(Server.MapPath("/Files/" + subgoalId + "/"), fileName);
            return File(filepath, MimeMapping.GetMimeMapping(filepath), fileName);
        }

        public ActionResult DeleteFile(string fileName, int subgoalId)
        {
            var filepath = Path.Combine(Server.MapPath("/Files/" + subgoalId + "/"), fileName);
            FileInfo oFileInfo = new FileInfo(filepath);
            oFileInfo.Delete();
            return RedirectToAction("Download/", new {subgoalId = subgoalId } );
        } 

        private void UpdateComletness(Subgoal subgoal , bool isDelete)
        {
            if (isDelete)
            {

            }
            var goal = db.Goal.Find(subgoal.Goal.Id);            
            var subgoals = db.Subgoal.Where(s => s.Goal.Id == subgoal.Goal.Id);
            int countsubgoal = subgoals.Count();       
            var complite = subgoals.Where(s => s.AtTerm == true);
            int countCoplite = complite.Count();
            if (isDelete)
            {
                if (subgoal.AtTerm == true)
                {
                    countCoplite = countCoplite - 1;
                }
               countsubgoal = countsubgoal - 1;
               
            }
            if (countCoplite == 0)
            {
                goal.Completeness = 0;
                goal.Name = goal.Name;
               
            }
            else
            {
                int copleteness = 100 / countsubgoal * countCoplite;
                goal.Completeness = copleteness;
                goal.Name = goal.Name;
            }      
                      
            db.Entry(goal).State = EntityState.Modified;
            db.SaveChanges();
        }

        private void SendSMSNotification(Subgoal subgoal)
        {
            if (UserManager.SmsService != null && subgoal.Student.PhoneNumber != null)
            {
                var message = new IdentityMessage
                {
                    Destination = subgoal.Student.PhoneNumber,
                    Body = "Your security code is: "
                };
                UserManager.SmsService.Send(message);
            }
        }

        [Authorize(Roles = "teacher")]
        public ActionResult CreateSubgoal()
        {
            
        
            var users = new ApplicationDbContext().Users;
            var rolesIdToUser = new ApplicationDbContext().Roles.Where(p => p.Name == "student").SelectMany(p => p.Users).ToList();
            var students = rolesIdToUser.Select(i => users.FirstOrDefault(u => u.Id == i.UserId)).ToList();
            ViewBag.Students = from student in students select new { Id = student.Id, FullName = student.FirstName + " " + student.LastName };
            
            return View();
        }

        [Authorize(Roles = "teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSubgoal( CreateSubgoalModel subgoalview, int id)
        {

            if (ModelState.IsValid)
            {
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                var subgoal = new Subgoal() { Name = subgoalview.name, Student = db.Users.Find(subgoalview.student_id), Description = subgoalview.description, EndDate = subgoalview.endDate };
                subgoal.Goal = db.Goal.First(c => c.Id == id);
                subgoal.Overdue = false;
                subgoal.AtTerm = false;
                db.Subgoal.Add(subgoal);
                db.SaveChanges();
                UpdateComletness(subgoal, false);
                SendSMSNotification(subgoal);
                return RedirectToAction("Details/" + subgoal.Goal.Id, "Goal");
            }
            return View(subgoalview);            
        }

        public ActionResult SubgoalList(int goalId)
        {
            List<Subgoal> subgoal = new List<Subgoal>();
            ViewBag.GoalId = goalId;
           
            foreach (var item in db.Subgoal.ToList())
            {
                if (item.Goal.Id == goalId)
                {
                    subgoal.Add(item);
                   
                }
            }
            return View(subgoal);
        }

        public ActionResult SubgoalFinish(int id)
        {
            var subgoal = db.Subgoal.FirstOrDefault(s => s.Id == id);
            
            subgoal.AtTerm = true;

            SendSMSNotification(subgoal);
            db.SaveChanges();
            UpdateComletness(subgoal , false);
            return RedirectToAction("Details/" + subgoal.Goal.Id, "Goal");

        }

        [Authorize(Roles = "teacher")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subgoal subgoal = db.Subgoal.Find(id);           

IndividualTaskManagement/Views/Shared/_Layout.cshtml
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery") 
  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/fonts/font-awesome/css/font-awesome.css">    
    <link rel="stylesheet" href="~/css/theme.css">
    <link rel="stylesheet" href="~/css/theme-elements.css">
    <link rel="stylesheet" href="~/css/theme-animate.css">  
    <link rel="stylesheet" href="~/css/skins/blue.css">  
    <link rel="stylesheet" href="~/css/custom.css">  
    <link rel="stylesheet" href="~/css/theme-responsive.css" />
    <link rel="stylesheet" href="~/css/ie.css">   
    <link rel="stylesheet" href="~/vendor/owl-carousel/owl.carousel.css" media="screen">
    <link rel="stylesheet" href="~/vendor/owl-carousel/owl.theme.css" media="screen">
    <link rel="stylesheet" href="~/vendor/magnific-popup/magnific-popup.css" media="screen">
    <link rel="stylesheet" href="~/vendor/rs-plugin/css/settings.css" media="screen">
    <link rel="stylesheet" href="~/vendor/circle-flip-slideshow/css/component.css" media="screen">  
    <script src="~/vendor/modernizr.js"></script>   
    <script src="~/vendor/respond.js"></script>   
    <script src="~/vendor/jquery.validate.js"></script> 
    <script src="~/vendor/jquery.easing.js"></script>
    <script src="~/vendor/jquery.appear.js"></script>
    <script src="~/vendor/jquery.cookie.js"></script>
    @*<script src="~/vendor/bootstrap.js"></script>*@
    <script src="~/vendor/twitterjs/twitter.js"></script>
    <script src="~/vendor/owl-carousel/owl.carousel.js"></script>   
    <script src="~/vendor/magnific-popup/magnific-popup.js"></script>  
    <script src="~/js/plugins.js"></script>
    <script src="~/js/theme.js"></script>
    @*<script src="~/js/custom.js"></script>*@
</head>

<header>
    <div class="container">   
            <nav>
                <ul class="nav nav-pills nav-top">
                    <li>
                        <a href="~/Home/About"><i class="icon icon-angle-right"></i>О проекте</a>
                    </li>
                    <li>
                        <a href="~/Home/Contact"><i class="icon icon-angle-right"></i>Контакты</a>
                    </li>
                    <li class="phone">
                        <span><i class="icon icon-phone"></i>(050) 67 35 103</span>
                    </li>
                </ul>
            </nav>

            <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
                <i class="icon icon-bars"></i>
            </button>
        </div>
    <div class="navbar-collapse nav-main-collapse collapse">
        <div class="container">

            <div class="social-icons">

                <ul class="social-icons">
                    <li class="facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook">Facebook</a></li>
                    <li class="vk"><a href="https://vk.com/andrewdobrelya" target="_blank" title="VK">VK</a></li>
                    <li class="github"><a href="https://github.com/WarGeH/RBRK/tree/master/Homeschooledsystem" target="_blank" title="Github">Github</a></li>
                </ul>
            </div>


            @Html.Partial("_LoginPartial")
            <nav class="nav-main mega-menu">
                <ul class="nav nav-pills nav-main" id="mainMenu">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>

                    @if (User.IsInRole("teacher"))
                    {
                        <li>@Html.ActionLink("Tasks", "Index", "Goal")</li>
                    }
                 
                    @if (User.IsInRole("student"))
                    {
                        <li>@Html.ActionLink("All tasks", "Index", "Subgoal")</li>
                    }
                  
                </ul>
            </nav>
        </div>
    </div>
</header>
<div class="container body-content">
    @RenderBody()
    <div class="modal">
    </div>
</div>
@RenderSection("scripts", required: false)